# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Ground Spring Builder', kernelModule='ballast_spring', kernelFunction='ballastspring', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Model Name', keyword='modelname', default='Model-1')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Instant Name', keyword='instanname', default='sleeper')
RsgTextField(p='DialogBox', fieldType='String', ncols=12, labelText='Set Name', keyword='setname', default='')
RsgTextField(p='DialogBox', fieldType='Integer', ncols=12, labelText='Section no.', keyword='sc', default='1')
RsgSeparator(p='DialogBox')
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Spring Parameter', layout='0')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Spring Stiffness', keyword='springstiff', default='')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Dashpot Coefficient', keyword='dashpotcoef', default='')
RsgSeparator(p='GroupBox_1')
RsgGroupBox(name='GroupBox_3', p='DialogBox', text='Reference Point ', layout='0')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Offset', keyword='offset', default='0.01')
RsgTextField(p='GroupBox_3', fieldType='Float', ncols=12, labelText='Mass', keyword='mass', default='0.01')
dialogBox.show()